= Pivotal OSS Build Schema for Apache HTTP Server

Copyright (c) 2017 Pivotal Software, Inc.

Pivotal licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

== Overview

Builds are monolithic. These rely on many established
components shipped with modern linux distributions
which are reasonably stable and up to date. On Windows,
every component must be built from source.

The build target is /opt/pivotal/webserver/httpd-2.4/
on Linux and Windows, but is relocatable. Each has a
long pathname, e.g. httpd-2.4.25-$bldno/ which is
symlinked from the 'expected' path. Non-release builds
have additional pathname components such as -snapshot,
-bleed, etc, and may have a TAG to distinguish two
otherwise apparently identical builds.

Build {pkg} reflects the particular component, either
the offical designation (httpd-2.4.25/), an indication
of interim packages (httpd-2.4.26-rc1/), or the exact
province of the file (httpd-2.4.26-dev-r1872199/)

Several {bld} schemas are expected; 'release' for the
official packages, 'candidate' for packages anticipated
for release, 'snapshot' for the working trees of the
component's current maintenance trees, and 'bleed' for
next-major or minor development trees.

mak/                   Build script files

src/                   Complete build sources
  {pkg}/               Component source (for VPATH build)
  pkgs/                Source component package downloads
  {bld}-manifest-vars  Description of {pkg} names and versions for {bld}

bld/                   Build trees of components by build type
  {pkg}/               Component build tree (vpath or copied from src/)

dst/                   Resulting intermediate binary packages
  {httpd-pkg}{tag}/    Temporary installation for testing and relocation

out/                   Final binary package
  {httpd-pkg}{tag}/    Relocateable binaries for distribution


== Phase 1: Gather Sources

$ cd src/
$ make Makefile.gather [BLD={type}] all

BLD defines the build type: release - candidate - snapshot - bleed
(case sensitive) where release is the default.

Gathers source code packages or (source checkouts) for all packages
into the source tree, and generates a version and directory name manifest.

Each component is designed for persistence, if from git or svn it performs
a fetch / update, if from a most recent release package, it fetches and
unpacks the package. The source directory tree is designed for parallelism,
the different build types may coexist in the same source tree.

This makefile is run first from the source directory root (e.g. src/),
and must be performed only upon updates to the source packages.
The resulting manifest can be compared to the previously created manifest
to determine if the sources have been updated.

Makefile.preconfig should follow immediately when the manifest changes.

== Phase 2: Preconfigure Sources

$ cd src/
$ make Makefile.preconfig [BLD={type}] all

Prepare configuration scripts of packages, particularly from source control
where autoconf etc have not been invoked yet.

This makefile is run after Makefile.gather from the source directory root,
and must be performed following updates to the source packages as indicated
by manifest changes. Only source code packages corresponding to the specific
BLD target are updated.

The result of this step is suitable for archive, or escrow and distribution
to multiple build systems, beginning at the Makefile.build step.

== Phase 3: Build Sources

$ cd bld/
$ make Makefile.build [BLD={type}] [TAG={-suffix}] all

Build all components described by the manifest into the intermediate/
temporary installation tree, using that intermediate tree as the component
reference for later components.

TAG defines the target directory and package name suffix such as a datestamp,
checkout revision, or continuous build revision number. By default there is
no suffix tag.

This makefile is run after Makefile.gather and Makefile.preconfig and may
be based on a snapshot of the build tree from those two previous steps from
another continuous build job.

This makefile must be run from the build (not source) subdirectory, such
as bld/. The build tree uses the same component directory names as the
source tree. The components are initially installed into the DESTDIR
which is the ../dst/httpd component directory name with the TAG variable
suffixed. SRCDIR references the source tree (typically ../src) and would
typically not need to be overridden.

The TARGET directory, /opt/pivotal/webserver/$(httpd_srcdir)$(TAG) would
typically not be overridden, and refers to the anticipated installation
path of the resulting package.

== Phase 4: Test Source and Intermediate Installation

$ cd bld/
$ make Makefile.test [BLD={type}] [TAG={-suffix}] all

Test all components described by the manifest and the intermediate/
temporary installation httpd server.

This makefile must be run from the build (not source) subdirectory.
Where a component has an integrated test target these are processed
within the build tree. The Apache httpd perl test framework is invoked
against the intermediate installation in the $DESTDIR path.



