# VMware OSS Build Schema for Apache HTTP Server
# 
# Copyright (c) 2017-2020 VMware, Inc.
#
# This program and the accompanying materials are made available under
# the terms of the under the Apache License, Version 2.0 (the "License”);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Makefile.package : Convert the target build from a fixed to a relocatable
#                    package, adding the instance deployment schema.
#
# BLD defines the build type: release - candidate - snapshot - bleed
# TAG defines the target directory and package name suffixes
# OPT declares optimization of verified parallel builds (-j4 by default)
#
# This makefile is run after Makefile.build
#
# This makefile must be run from the package (not build or dest) subdirectory,
# the build tree uses the same component directory names as the source tree
# The binary components are collected from the DESTDIR which is the
# ../dst/httpd component directory name with the TAG variable suffixed
# and prepared into the PKGDIR (httpd{TAG}) directory of the current tree

BLD=release
TAG=

SRCDIR=$(shell cd ..; pwd)/src

include $(SRCDIR)/$(BLD)-manifest-vars

DESTDIR=$(shell cd ..; pwd)/dst/$(httpd_srcdir)$(TAG)
PKGDIR=$(httpd_srcdir)$(TAG)

OBJCOPY=objcopy

all: package-httpd

pre-package:
	-rm -rf $(PKGDIR) 2>/dev/null

collect-httpd: pre-package
	cp -prf $(DESTDIR) $(PKGDIR)
	perl ../instance-conf/httpd-2.4/bin/fixrootpath.pl \
		--srcdir=$(DESTDIR) \
		--dstdir=@@PRODUCT_ROOT@@/$(httpd_srcdir)$(TAG) $(PKGDIR)
	perl ../instance-conf/httpd-2.4/bin/fixrootpath.pl \
		--srcdir=/opt/apache/webserver/httpd-2.4 \
		--dstdir=@@PRODUCT_ROOT@@/$(httpd_srcdir)$(TAG) $(PKGDIR)

prepare-instance: collect-httpd
	mkdir $(PKGDIR)/_instance
	mv $(PKGDIR)/conf $(PKGDIR)/_instance/conf
	mv $(PKGDIR)/cgi-bin $(PKGDIR)/_instance/cgi-bin
	mv $(PKGDIR)/htdocs $(PKGDIR)/_instance/htdocs
	mv $(PKGDIR)/logs $(PKGDIR)/_instance/logs
	# The global binary directory ssl/ contents are not relocated
	mkdir $(PKGDIR)/_instance/ssl
	chmod 700 $(PKGDIR)/_instance/ssl
	cp -p ../instance-conf/httpd-2.4/bin/*.pl $(PKGDIR)/bin/
	cp -p ../instance-conf/httpd-2.4/bin/*.sh $(PKGDIR)/bin/
	cp -prf ../instance-conf/httpd-2.4/_instance/* $(PKGDIR)/_instance/
	rm $(PKGDIR)/_instance/bin/*.ps1
# Un-windows any potentially DOS formatted utf8/crlf files;
	LC_ALL=C sed -e '1s#^\xEF\xBB\xBF##;s#\r$$##;' \
	   -i $(PKGDIR)/bin/fixrootpath.pl
	LC_ALL=C sed -e '1s#^\xEF\xBB\xBF##;s#\r$$##;' \
	   -i $(PKGDIR)/bin/newserver.pl
	LC_ALL=C sed -e '1s#^\xEF\xBB\xBF##;s#\r$$##;' \
	   -i $(PKGDIR)/bin/httpdenv.sh
	LC_ALL=C sed -e '1s#^\xEF\xBB\xBF##;s#\r$$##;' \
	   -i $(PKGDIR)/_instance/bin/httpdctl
	LC_ALL=C sed -e '1s#^\xEF\xBB\xBF##;s#\r$$##;' \
	   -i $(PKGDIR)/_instance/bin/httpdenv.sh

strip-symbols:
# collect-httpd
ifdef OBJCOPY
	cd $(PKGDIR) && \
	for x in `find . -type f`; do \
	  if expr \( \( `expr "$$x" : ".*\.debug\$$"` = 0 \) \
		  \& \( "`file $$x`" : ".*not stripped" \) \) >/dev/null; then \
	    if test \! -f $$x.debug -a \! -h $$x; then ( \
	      chmod u+w $$x && \
	      cp -pf $$x $$x.orig && \
	      printf Extracting...\  && \
	      $(OBJCOPY) --only-keep-debug $$x $$x.debug && \
	      touch -r $$x $$x.debug && \
	      printf stripping...\  && \
	      $(OBJCOPY) --strip-debug $$x && \
	      printf linking...\  && \
	      $(OBJCOPY) --add-gnu-debuglink=$$x.debug $$x && \
	      touch -r $$x.debug $$x && \
	      rm -f $$x.orig && \
	      echo \ Split $$x.debug; \
	      if test $$? -gt 0; then ( \
		rm -f $$x $$x.debug; \
		mv $$x.orig $$x; \
		echo \ Skipped $$x.debug; \
	      ); fi; \
	    ); fi; \
	  fi; \
	done; \
	cd ..
endif

package-httpd: collect-httpd strip-symbols prepare-instance
	tar -cjvf $(PKGDIR).tar.bz2 $(PKGDIR)


