# Pivotal OSS Build Schema for Apache HTTP Server
#
# Copyright (C) 2017-Present Pivotal Software, Inc. All rights reserved.
#
# This program and the accompanying materials are made available under
# the terms of the under the Apache License, Version 2.0 (the "License”);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Makefile.build : Build all components described by the manifest in the
#                  source tree.
#
# BLD defines the build type: release - candidate - snapshot - bleed
# TAG defines the target directory and package name suffixes
# OPT declares optimization of verified parallel builds (-j4 by default)
#
# This makefile is run after Makefile.gather and Makefile.preconfig
#
# This makefile must be run from the build (not source) subdirectory,
# the build tree uses the same component directory names as the source tree
# The components are initially installed into the DESTDIR which is the
# ../dst/httpd component directory name with the TAG variable suffixed.

BLD=release
TAG=
OPT=-j4
SRCDIR=$(shell cd ..; pwd)/src

include $(SRCDIR)/$(BLD)-manifest-vars

DESTDIR=$(shell cd ..; pwd)/dst/$(httpd_srcdir)$(TAG)
TARGET=/opt/pivotal/webserver/$(httpd_srcdir)$(TAG)

CMAKE_DEFAULTS=-G "Unix Makefiles" -D CMAKE_COLOR_MAKEFILE=OFF
PREFER_CMAKE=0

all: build-httpd

pre-build:
	-mkdir -p $(DESTDIR) 2>/dev/null
	echo $(SRCDIR)


ifndef expat_srcdir
with_expat=
build-expat:
else
with_expat=--with-expat=$(DESTDIR)
$(expat_srcdir)/Makefile: $(SRCDIR)/$(expat_srcdir)/expat/configure
        -mkdir $(expat_srcdir) 2>/dev/null
        cd $(expat_srcdir) && \
	  $(SRCDIR)/$(expat_srcdir)/expat/configure \
		 --prefix=$(DESTDIR) && \
        cd ..

build-expat: $(expat_srcdir)/Makefile
	cd $(expat_srcdir) && \
	  make $(OPT) && \
	  make $(OPT) install && \
	cd ..
endif


$(apr_srcdir)/Makefile: build-openssl $(SRCDIR)/$(apr_srcdir)/configure
	-mkdir $(apr_srcdir) 2>/dev/null
	cd $(apr_srcdir) && \
	  $(SRCDIR)/$(apr_srcdir)/configure \
		 --with-openssl=$(DESTDIR) \
		 --with-crypto \
		 --without-ldap \
		 --without-lber \
		 --with-installbuilddir=\$${prefix}/build \
		 --includedir=\$${prefix}/include \
		 --prefix=$(DESTDIR) && \
	cd ..

build-apr: $(apr_srcdir)/Makefile
	cd $(apr_srcdir) && \
	  make $(OPT) && \
	  make $(OPT) install && \
	cd ..


ifndef aprutil_srcdir
with_aprutil=
build-aprutil: build-apr
else
with_aprutil=--with-apr-util=$(DESTDIR)
$(aprutil_srcdir)/Makefile: build-openssl build-apr \
			    $(SRCDIR)/$(aprutil_srcdir)/configure
	-mkdir $(aprutil_srcdir) 2>/dev/null
	cd $(aprutil_srcdir) && \
	  $(SRCDIR)/$(aprutil_srcdir)/configure \
		 --with-apr=$(DESTDIR) \
		 --with-openssl=$(DESTDIR) \
		 --with-crypto \
		 --without-ldap \
		 --without-lber \
		 --with-installbuilddir=\$${prefix}/build \
		 --includedir=\$${prefix}/include \
		 --prefix=$(DESTDIR) && \
	cd ..

build-aprutil: build-apr $(aprutil_srcdir)/Makefile
	cd $(aprutil_srcdir) && \
	  make $(OPT) && \
	  make $(OPT) install && \
	cd ..
endif


# Ancient openssl 1.0.2 did not support vpath builds or concurrent builds
ifeq "$(patsubst 1.0.%,,$(openssl_ver))" ""
$(openssl_srcdir)/Makefile: $(firstword $(MAKEFILE_LIST)) \
			    $(SRCDIR)/$(openssl_srcdir)
	-mkdir $(openssl_srcdir) 2>/dev/null
	cp -prf $(SRCDIR)/$(openssl_srcdir)/* $(openssl_srcdir)/
	cd $(openssl_srcdir) && \
	  ./config --prefix=$(DESTDIR) shared \
		   -I$(DESTDIR)/include -L$(DESTDIR)/lib \
		   -Wl,-rpath,$(TARGET)/lib && \
	cd ..

build-openssl: $(openssl_srcdir)/Makefile
	cd $(openssl_srcdir) && \
	  make && \
	  make install && \
	cd ..
else
$(openssl_srcdir)/Makefile: $(SRCDIR)/$(openssl_srcdir)/Configure
	-mkdir $(openssl_srcdir) 2>/dev/null
	cd $(openssl_srcdir) && \
	  $(SRCDIR)/$(openssl_srcdir)/config shared \
		 --libdir=lib --prefix=$(DESTDIR) \
		 -Wl,-rpath,$(TARGET)/lib && \
	cd ..

build-openssl: $(openssl_srcdir)/Makefile
	cd $(openssl_srcdir) && \
	  make $(OPT) && \
	  make $(OPT) install && \
	cd ..
endif


ifndef brotli_srcdir
build-brotli:
else
$(brotli_srcdir)/Makefile: $(SRCDIR)/$(brotli_srcdir)
	-mkdir $(brotli_srcdir) 2>/dev/null
	cd $(brotli_srcdir) && \
	  cmake -G "Unix Makefiles" \
		-D CMAKE_INSTALL_LIBDIR=lib \
		-D CMAKE_INSTALL_PREFIX=$(DESTDIR) \
		$(SRCDIR)/$(brotli_srcdir) && \
	cd ..

build-brotli: $(brotli_srcdir)/Makefile
	cd $(brotli_srcdir) && \
	  make $(OPT) && \
	  make $(OPT) install && \
	cd ..
endif


$(nghttp2_srcdir)/Makefile: $(SRCDIR)/$(nghttp2_srcdir)/configure
	-mkdir $(nghttp2_srcdir) 2>/dev/null
	cd $(nghttp2_srcdir) && \
	  $(SRCDIR)/$(nghttp2_srcdir)/configure \
		 --enable-lib-only \
		 --prefix=$(DESTDIR) && \
	cd ..

build-nghttp2: $(nghttp2_srcdir)/Makefile
	cd $(nghttp2_srcdir) && \
	  make $(OPT) && \
	  make $(OPT) install && \
	cd ..

# Explicitly enabling version and unixd as built-in on Unix, enabling suexec,
# cgi for prefork configs, and authnz-fcgi and proxy-http2 for early adopters.
#
# Explicitly disabling dialup, echo and reflector as experimental/test
# and disabling ldap because lber depends on openssl, and the system openssl
# used by openldap conflicts with the most modern openssl in this build
#
$(httpd_srcdir)/Makefile: build-apr build-aprutil build-openssl \
			  build-brotli build-nghttp2 \
			  $(SRCDIR)/$(httpd_srcdir)/configure
	-mkdir $(httpd_srcdir) 2>/dev/null
	cd $(httpd_srcdir) && \
	  $(SRCDIR)/$(httpd_srcdir)/configure \
		 --prefix=$(DESTDIR) \
		 --with-apr=$(DESTDIR) $(with_aprutil) \
		 --with-openssl=$(DESTDIR) \
		 --with-nghttp2=$(DESTDIR) \
		 --with-brotli=$(DESTDIR) \
		 --enable-mods-shared=all \
		 --enable-mpms-shared=all \
		 --enable-load-all-modules \
		 --enable-unixd=static \
		 --enable-version=static \
		 --disable-authnz-ldap \
		 --disable-ldap \
		 --disable-dialup \
		 --disable-echo \
		 --disable-reflector \
		 --enable-cgi=shared \
		 --enable-authnz-fcgi=shared \
		 --enable-proxy-http2=shared \
		 --enable-suexec=shared \
		 --with-suexec-caller=httpd \
		 --with-suexec-bin=$(TARGET)/bin/suexec		\
		 --with-suexec-docroot=$(TARGET)/suexec-cgi-bin	\
		 --with-suexec-logfile=$(TARGET)/logs/suexec.log \
		 --with-mpm=event && \
	cd ..

build-httpd: $(httpd_srcdir)/Makefile
	cd $(httpd_srcdir) && \
	  make $(OPT) && \
	  make $(OPT) install && \
	  sed "s/\(LoadModule mpm_\(worker\|prefork\)\)/#\1/" \
		< $(DESTDIR)/conf/original/httpd.conf \
		> $(DESTDIR)/conf/httpd.conf && \
	cd ..


ifndef tcnative_srcdir
build-tcnative:
else
$(tcnative_srcdir)/Makefile: build-apr build-openssl \
			     $(SRCDIR)/$(tcnative_srcdir)/native/configure
	-mkdir $(tcnative_srcdir) 2>/dev/null
	cd $(tcnative_srcdir) && \
	  $(SRCDIR)/$(tcnative_srcdir)/native/configure \
		 --with-apr=$(DESTDIR) \
		 --with-ssl=$(DESTDIR) \
		 --prefix=$(DESTDIR) && \
	cd ..

build-tcnative: $(tcnative_srcdir)/Makefile
	cd $(tcnative_srcdir) && \
	  make $(OPT) && \
	  make $(OPT) install && \
	cd ..
endif


