# Pivotal OSS Build Schema for Apache HTTP Server
#
# Copyright (C) 2017-Present Pivotal Software, Inc. All rights reserved.
#
# This program and the accompanying materials are made available under
# the terms of the under the Apache License, Version 2.0 (the "License”);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Makefile.gather : Gather source code packages or (source checkouts)
#                   for all packages into the source tree, and generate
#                   a version and directory name manifest
#
# BLD defines the build type: release - candidate - snapshot - bleed
#
# This makefile is run first from the source directory root, and must be
# performed following updates to the source packages. Makefile.preconfig
# in the same directory should follow immediately if the manifest changes.

BLD=release

all: gather-linux-$(BLD)

pre-manifest:
	-mkdir pkgs 2>/dev/null
	echo Gathering $(BLD) Source Trees
	truncate -s0 $(BLD)-manifest-vars

gather-httpdtest-trunk: pre-manifest
	httpdtest_srcpath=https://svn.apache.org/repos/asf/httpd/test/framework/trunk && \
	if test ! -d httpdtest-trunk ; then \
	  svn co -q $$httpdtest_srcpath httpdtest-trunk; \
	else \
	  svn up -q httpdtest-trunk; \
	fi && \
	echo httpdtest_srcdir=httpdtest-trunk >>$(BLD)-manifest-vars && \
	echo httpdtest_ver=httpdtest-trunk >>$(BLD)-manifest-vars

gather-httpd-release: pre-manifest
	httpd_srcpath=https://www.apache.org/dist/httpd && \
	httpd_pkg=`wget -q -O - $$httpd_srcpath/ | sed -n '/<a href="\(httpd-2\.4\.[0-9]*\.tar\.bz2\)"/{s#.*href="\([^"]*\).*#\1#;h};$$!b;g;p'` && \
	httpd_ver=`echo $$httpd_pkg | sed 's#httpd-\(.*\)\.tar\.bz2#\1#;'` && \
	httpd_srcdir=httpd-$$httpd_ver && \
	if test ! -f pkgs/$$httpd_pkg; then \
	  cd pkgs && \
	  wget -nv $$httpd_srcpath/$$httpd_pkg && \
	  wget -nv $$httpd_srcpath/$$httpd_pkg.asc && \
	  cd .. && \
          tar -xjf pkgs/$$httpd_pkg; \
	fi && \
	echo httpd_srcdir=$$httpd_srcdir >>$(BLD)-manifest-vars && \
	echo httpd_ver=$$httpd_ver >>$(BLD)-manifest-vars

gather-httpd-2xbranch: pre-manifest
	httpd_srcpath=https://svn.apache.org/repos/asf/httpd/httpd/branches/2.4.x && \
	httpd_rev=`svn info $$httpd_srcpath | sed -n '/Last Changed Rev: \([0-9]\+\)/{s#.*: ##;p}'` && \
	httpd_ver=2.4.x-$$httpd_rev && \
	httpd_srcdir=httpd-$$httpd_ver && \
	if test ! -d $$httpd_srcdir; then \
	  svn co -q -r $$httpd_rev $$httpd_srcpath $$httpd_srcdir; \
	fi && \
	echo httpd_srcdir=$$httpd_srcdir >>$(BLD)-manifest-vars && \
	echo httpd_ver=$$httpd_ver >>$(BLD)-manifest-vars

gather-httpd-trunk: pre-manifest
	httpd_srcpath=https://svn.apache.org/repos/asf/httpd/httpd/trunk && \
	httpd_rev=`svn info $$httpd_srcpath | sed -n '/Last Changed Rev: \([0-9]\+\)/{s#.*: ##;p}'` && \
	httpd_ver=2.5.x-$$httpd_rev && \
	httpd_srcdir=httpd-$$httpd_ver && \
	if test ! -d $$httpd_srcdir; then \
	  svn co -q -r $$httpd_rev $$httpd_srcpath $$httpd_srcdir; \
	fi && \
	echo httpd_srcdir=$$httpd_srcdir >>$(BLD)-manifest-vars && \
	echo httpd_ver=$$httpd_ver >>$(BLD)-manifest-vars

gather-tcnative-release: pre-manifest
	tcnative_srcpath=https://www.apache.org/dist/tomcat/tomcat-connectors/native && \
	tcnative_ver=`wget -q -O - $$tcnative_srcpath/ | sed -n '/<a href="\(1\.2\.[0-9]*\/\)"/{s#.*href="\([^"/]*\)\/.*#\1#;h};$$!b;g;p'` && \
	tcnative_srcpath=$$tcnative_srcpath/$$tcnative_ver/source && \
	tcnative_srcdir=tomcat-native-$$tcnative_ver-src && \
	tcnative_pkg=$$tcnative_srcdir.tar.gz && \
	if test ! -f pkgs/$$tcnative_pkg; then \
	  cd pkgs && \
	  wget -nv $$tcnative_srcpath/$$tcnative_pkg && \
	  wget -nv $$tcnative_srcpath/$$tcnative_pkg.asc && \
	  cd .. && \
	  tar -xzf pkgs/$$tcnative_pkg; \
	fi && \
	echo tcnative_srcdir=$$tcnative_srcdir >>$(BLD)-manifest-vars && \
	echo tcnative_ver=$$tcnative_ver >>$(BLD)-manifest-vars

gather-tcnative-trunk: pre-manifest
	tcnative_srcpath=https://svn.apache.org/repos/asf/tomcat/native/trunk && \
	tcnative_rev=`svn info $$tcnative_srcpath | sed -n '/Last Changed Rev: \([0-9]\+\)/{s#.*: ##;p}'` && \
	tcnative_ver=1.2.x-$$tcnative_rev && \
	tcnative_srcdir=tomcat-native-$$tcnative_ver && \
	if test ! -d $$tcnative_srcdir ; then \
	  svn co -q $$tcnative_srcpath $$tcnative_srcdir; \
	fi && \
	echo tcnative_srcdir=$$tcnative_srcdir >>$(BLD)-manifest-vars && \
	echo tcnative_ver=$$tcnative_ver >>$(BLD)-manifest-vars

gather-apr-release: pre-manifest
	apr_srcpath=https://www.apache.org/dist/apr && \
	apr_pkg=`wget -q -O - $$apr_srcpath/ | sed -n '/<a href="\(apr-1\.[0-9]\.[0-9]*\.tar\.bz2\)"/{s#.*href="\([^"]*\).*#\1#;h};$$!b;g;p'` && \
	apr_ver=`echo $$apr_pkg | sed 's#apr-\(.*\)\.tar\.bz2#\1#;'` && \
	apr_srcdir=apr-$$apr_ver && \
	if test ! -f pkgs/$$apr_pkg; then \
	  cd pkgs && \
	  wget -nv $$apr_srcpath/$$apr_pkg && \
	  wget -nv $$apr_srcpath/$$apr_pkg.asc && \
	  cd .. && \
	  tar -xjf pkgs/$$apr_pkg; \
	fi && \
	echo apr_srcdir=$$apr_srcdir >>$(BLD)-manifest-vars && \
	echo apr_ver=$$apr_ver >>$(BLD)-manifest-vars

gather-apr-1xbranch: pre-manifest
	apr_srcpath=https://svn.apache.org/repos/asf/apr/apr/branches/1.7.x && \
	apr_rev=`svn info $$apr_srcpath | sed -n '/Last Changed Rev: \([0-9]\+\)/{s#.*: ##;p}'` && \
	apr_ver=1.7.x-$$apr_rev && \
	apr_srcdir=apr-$$apr_ver && \
	if test ! -d $$apr_srcdir ; then \
	  svn co -q $$apr_srcpath $$apr_srcdir; \
	fi && \
	echo apr_srcdir=$$apr_srcdir >>$(BLD)-manifest-vars && \
	echo apr_ver=$$apr_ver >>$(BLD)-manifest-vars

gather-apr-trunk: pre-manifest
	apr_srcpath=https://svn.apache.org/repos/asf/apr/apr/trunk && \
	apr_rev=`svn info $$apr_srcpath | sed -n '/Last Changed Rev: \([0-9]\+\)/{s#.*: ##;p}'` && \
	apr_ver=2.0.x-$$apr_rev && \
	apr_srcdir=apr-$$apr_ver && \
	if test ! -d $$apr_srcdir ; then \
	  svn co -q $$apr_srcpath $$apr_srcdir; \
	fi && \
	echo apr_srcdir=$$apr_srcdir >>$(BLD)-manifest-vars && \
	echo apr_ver=$$apr_ver >>$(BLD)-manifest-vars

gather-aprutil-release: pre-manifest
	aprutil_srcpath=https://www.apache.org/dist/apr && \
	aprutil_pkg=`wget -q -O - $$aprutil_srcpath/ | sed -n '/<a href="\(apr-util-1\.[0-9]\.[0-9]*\.tar\.bz2\)"/{s#.*href="\([^"]*\).*#\1#;h};$$!b;g;p'` && \
	aprutil_ver=`echo $$aprutil_pkg | sed 's#apr-util-\(.*\)\.tar\.bz2#\1#;'` && \
	if test ! -f pkgs/$$aprutil_pkg; then \
	  cd pkgs && \
	  wget -nv $$aprutil_srcpath/$$aprutil_pkg && \
	  wget -nv $$aprutil_srcpath/$$aprutil_pkg.asc && \
	  cd .. && \
	  tar -xjf pkgs/$$aprutil_pkg; \
	fi && \
	echo aprutil_srcdir=apr-util-$$aprutil_ver >>$(BLD)-manifest-vars && \
	echo aprutil_ver=$$aprutil_ver >>$(BLD)-manifest-vars

gather-aprutil-1xbranch: pre-manifest
	aprutil_srcpath=https://svn.apache.org/repos/asf/apr/apr-util/branches/1.6.x && \
	aprutil_rev=`svn info $$aprutil_srcpath | sed -n '/Last Changed Rev: \([0-9]\+\)/{s#.*: ##;p}'` && \
	aprutil_ver=1.6.x-$$aprutil_rev && \
	aprutil_srcdir=apr-util-$$aprutil_ver && \
	if test ! -d $$aprutil_srcdir ; then \
	  svn co -q $$aprutil_srcpath $$aprutil_srcdir; \
	fi && \
	echo aprutil_srcdir=$$aprutil_srcdir >>$(BLD)-manifest-vars && \
	echo aprutil_ver=$$aprutil_ver >>$(BLD)-manifest-vars

gather-aprutil-trunk: pre-manifest
#	NOOP - aprutil merges into apr

gather-openssl-release: pre-manifest
	openssl_srcpath=https://www.openssl.org/source && \
	openssl_pkg=`wget -q -O - $$openssl_srcpath/ | sed 's#.*<a href="\(openssl-1\.1\.0[a-z]*\.tar\.gz\)".*#\1#p;d;'` && \
	openssl_ver=`echo $$openssl_pkg | sed 's#openssl-\(.*\)\.tar\.gz#\1#;'` && \
	if test ! -f pkgs/$$openssl_pkg; then \
	  cd pkgs && \
	  wget -nv $$openssl_srcpath/$$openssl_pkg && \
	  wget -nv $$openssl_srcpath/$$openssl_pkg.asc && \
	  cd .. && \
	  tar -xzf pkgs/$$openssl_pkg; \
	fi && \
	echo openssl_srcdir=openssl-$$openssl_ver >>$(BLD)-manifest-vars && \
	echo openssl_ver=$$openssl_ver >>$(BLD)-manifest-vars

gather-openssl-110branch: pre-manifest
	openssl_srcpath=https://github.com/openssl/openssl && \
	if test ! -d openssl-1.1.0git ; then \
	  git clone -q $$openssl_srcpath.git openssl-1.1.0git && \
	  cd openssl-1.1.0git && git checkout OpenSSL_1_1_0-stable && cd ..; \
	else \
	  cd openssl-1.1.0git && git fetch -q && cd ..; \
	fi && \
	echo openssl_srcdir=openssl-1.1.0git >>$(BLD)-manifest-vars && \
	echo openssl_ver=1.1.0-git >>$(BLD)-manifest-vars

gather-openssl-master: pre-manifest
	openssl_srcpath=https://github.com/openssl/openssl && \
	if test ! -d openssl-master ; then \
	  git clone -q $$openssl_srcpath.git openssl-master; \
	else \
	  cd openssl-master && git fetch -q && cd ..; \
	fi && \
	echo openssl_srcdir=openssl-master >>$(BLD)-manifest-vars && \
	echo openssl_ver=1.x-git >>$(BLD)-manifest-vars

gather-nghttp2-release: pre-manifest
	nghttp2_srcpath=https://github.com/nghttp2/nghttp2/releases && \
	nghttp2_pkg=`wget --max-redirect=0 $$nghttp2_srcpath/latest/ 2>&1 | sed 's#Location: \(.*\)/tag/v\([^/]*\) \[following\]#\1/download/v\2/nghttp2-\2.tar.bz2#p;d;'` && \
	nghttp2_srcpath=`echo $$nghttp2_pkg | sed 's#/[^/]*$$##;'` && \
	nghttp2_pkg=`echo $$nghttp2_pkg | sed 's#.*/##;'` && \
	nghttp2_ver=`echo $$nghttp2_pkg | sed 's#nghttp2-\(.*\)\.tar\.bz2#\1#;'`&& \
	if test ! -f pkgs/$$nghttp2_pkg; then \
	  cd pkgs && \
	  wget -nv $$nghttp2_srcpath/$$nghttp2_pkg && \
	  cd .. && \
	  tar -xjf pkgs/$$nghttp2_pkg; \
	fi && \
	echo nghttp2_srcdir=nghttp2-$$nghttp2_ver >>$(BLD)-manifest-vars && \
	echo nghttp2_ver=$$nghttp2_ver >>$(BLD)-manifest-vars

gather-nghttp2-master: pre-manifest
	nghttp2_srcpath=https://github.com/tatsuhiro-t/nghttp2 && \
	if test ! -d nghttp2-master ; then \
	  git clone -q $$nghttp2_srcpath.git nghttp2-master; \
	else \
	  cd nghttp2-master && git fetch -q && cd ..; \
	fi && \
	echo nghttp2_srcdir=nghttp2-master >>$(BLD)-manifest-vars && \
	echo nghttp2_ver=1.x-git >>$(BLD)-manifest-vars

gather-brotli-release: pre-manifest
	brotli_srcpath=https://github.com/google/brotli/releases && \
	brotli_ver=`wget --max-redirect=0 $$brotli_srcpath/latest/ 2>&1 | sed 's#Location: .*/tag/v\([^/]*\) \[following\]#\1#p;d;'` && \
	brotli_srcpath=https://github.com/google/brotli/archive && \
	brotli_srcdir=brotli-$$brotli_ver && \
	brotli_pkg=$$brotli_srcdir.tar.gz && \
	if test ! -f pkgs/$$brotli_pkg; then \
	  cd pkgs && \
	  wget -nv $$brotli_srcpath/v$$brotli_ver.tar.gz -O $$brotli_pkg && \
	  cd .. && \
	  tar -xzf pkgs/$$brotli_pkg; \
	fi && \
	echo brotli_srcdir=$$brotli_srcdir >>$(BLD)-manifest-vars && \
	echo brotli_ver=$$brotli_ver >>$(BLD)-manifest-vars

gather-brotli-master: pre-manifest
	brotli_srcpath=https://github.com/google/brotli && \
	brotli_ver=1.x-git && \
	brotli_srcdir=brotli-$$brotli_ver && \
	if test ! -d $$brotli_srcdir ; then \
	  git clone -q $$brotli_srcpath.git $$brotli_srcdir; \
	else \
	  cd $$brotli_srcdir && git fetch -q && cd ..; \
	fi && \
	echo brotli_srcdir=$$brotli_srcdir >>$(BLD)-manifest-vars && \
	echo brotli_ver=$$brotli_ver >>$(BLD)-manifest-vars

gather-apriconv-release: pre-manifest
	apriconv_srcpath=https://www.apache.org/dist/apr && \
	apriconv_pkg=`wget -q -O - $$apriconv_srcpath/ | sed -n '/<a href="\(apr-iconv-1\.[0-9]\.[0-9]*\.tar\.bz2\)"/{s#.*href="\([^"]*\).*#\1#;h};$$!b;g;p'` && \
	apriconv_ver=`echo $$apriconv_pkg | sed 's#apr-iconv-\(.*\)\.tar\.bz2#\1#;'` && \
	if test ! -f pkgs/$$apriconv_pkg; then \
	  cd pkgs && \
	  wget -nv $$apriconv_srcpath/$$apriconv_pkg && \
	  wget -nv $$apriconv_srcpath/$$apriconv_pkg.asc && \
	  cd .. && \
	  tar -xjf pkgs/$$apriconv_pkg; \
	fi && \
	echo apriconv_srcdir=apr-iconv-$$apriconv_ver >>$(BLD)-manifest-vars && \
	echo apriconv_ver=$$apriconv_ver >>$(BLD)-manifest-vars

gather-apriconv-1xbranch: pre-manifest
	apriconv_srcpath=https://svn.apache.org/repos/asf/apr/apr-iconv/branches/1.6.x && \
	apriconv_rev=`svn info $$apriconv_srcpath | sed -n '/Last Changed Rev: \([0-9]\+\)/{s#.*: ##;p}'` && \
	apriconv_ver=1.2.x-$$apriconv_rev && \
	apriconv_srcdir=apr-iconv-$$apriconv_ver && \
	if test ! -d $$apriconv_srcdir ; then \
	  svn co -q $$apriconv_srcpath $$apriconv_srcdir; \
	fi && \
	echo apriconv_srcdir=$$apriconv_srcdir >>$(BLD)-manifest-vars && \
	echo apriconv_ver=$$apriconv_ver >>$(BLD)-manifest-vars

gather-expat-release: pre-manifest
	expat_srcpath=https://github.com/libexpat/libexpat/releases && \
	expat_ver=`wget -q -O - $$expat_srcpath | sed -n 's#^.*<a href=".*\/archive\/R_\(.*\)\.tar\.gz".*$$#\1#;t once;$$!b;:once;p;q;'` && \
	expat_srcpath=https://github.com/libexpat/libexpat/archive/R_$$expat_ver.tar.gz && \
	expat_srcdir=libexpat-R_$$expat_ver && \
	expat_pkg=$$expat_srcdir.tar.gz && \
        expat_ver=`echo $$expat_ver | sed "s#_#.#g"` && \
	if test ! -f pkgs/$$expat_pkg; then \
	  cd pkgs && \
	  wget -nv $$expat_srcpath -O $$expat_pkg && \
	  cd .. && \
	  tar -xzf pkgs/$$expat_pkg; \
	fi && \
	echo expat_srcdir=$$expat_srcdir >>$(BLD)-manifest-vars && \
	echo expat_ver=$$expat_ver >>$(BLD)-manifest-vars

gather-expat-master: pre-manifest
	expat_srcpath=https://github.com/libexpat/libexpat && \
	expat_ver=2.x-git && \
	expat_srcdir=libexpat-$$expat_ver && \
	if test ! -d $$expat_srcdir ; then \
	  git clone -q $$expat_srcpath.git $$expat_srcdir; \
	else \
	  cd $$expat_srcdir && git fetch -q && cd ..; \
	fi && \
	echo expat_srcdir=$$expat_srcdir >>$(BLD)-manifest-vars && \
	echo expat_ver=$$expat_ver >>$(BLD)-manifest-vars

gather-pcre-release: pre-manifest
	pcre_srcpath=https://ftp.pcre.org/pub/pcre/ &&\
	pcre_pkg=`wget -q -O - $$pcre_srcpath/ | sed -n '/<a href="\(pcre-8\.[0-9]*\.tar\.bz2\)"/{s#.*href="\([^"]*\).*#\1#;h};$$!b;g;p'` && \
	pcre_ver=`echo $$pcre_pkg | sed 's#pcre-\(.*\)\.tar\.bz2#\1#;'` && \
	if test ! -f pkgs/$$pcre_pkg; then \
	  cd pkgs && \
	  wget -nv $$pcre_srcpath/$$pcre_pkg && \
	  wget -nv $$pcre_srcpath/$$pcre_pkg.sig && \
	  cd .. && \
	  tar -xjf pkgs/$$pcre_pkg; \
	fi && \
	echo pcre_srcdir=pcre-$$pcre_ver >>$(BLD)-manifest-vars && \
	echo pcre_ver=$$pcre_ver >>$(BLD)-manifest-vars

gather-pcre-trunk: pre-manifest
	pcre_srcpath=svn://vcs.exim.org/pcre/code/trunk && \
	pcre_rev=`svn info $$pcre_srcpath | sed -n '/Last Changed Rev: \([0-9]\+\)/{s#.*: ##;p}'` && \
	pcre_ver=8.x-$$pcre_rev && \
	pcre_srcdir=pcre-$$pcre_ver && \
	if test ! -d $$pcre_srcdir; then \
	  svn co -q -r $$pcre_rev $$pcre_srcpath $$pcre_srcdir; \
	fi && \
	echo pcre_srcdir=$$pcre_srcdir >>$(BLD)-manifest-vars && \
	echo pcre_ver=$$pcre_ver >>$(BLD)-manifest-vars

# svn https://vcs.pcre.org/pcre/code/trunk/

gather-libxml2-release: pre-manifest

gather-lua-release: pre-manifest

gather-zlib-release: pre-manifest

gather-complete-release: gather-apriconv-release \
		      gather-expat-release gather-pcre-release \
		      gather-apr-release gather-aprutil-release \
		      gather-httpd-release gather-openssl-release \
		      gather-nghttp2-release gather-brotli-release \
		      gather-libxml2-release gather-lua-release \
		      gather-zlib-release gather-httpdtest-trunk
	mv $(BLD)-manifest-vars $(BLD)-manifest-vars.sav
	LC_COLLATE=C sort < $(BLD)-manifest-vars.sav > $(BLD)-manifest-vars
	rm $(BLD)-manifest-vars.sav

gather-linux-release: gather-apr-release gather-aprutil-release \
		      gather-httpd-release gather-openssl-release \
		      gather-nghttp2-release gather-brotli-release \
		      gather-httpdtest-trunk
	mv $(BLD)-manifest-vars $(BLD)-manifest-vars.sav
	LC_COLLATE=C sort < $(BLD)-manifest-vars.sav > $(BLD)-manifest-vars
	rm $(BLD)-manifest-vars.sav

gather-linux-candidate: gather-apr-release gather-aprutil-release \
		      gather-httpd-release gather-openssl-release \
		      gather-nghttp2-release gather-brotli-master \
		      gather-httpdtest-trunk
	mv $(BLD)-manifest-vars $(BLD)-manifest-vars.sav
	sort < $(BLD)-manifest-vars.sav > $(BLD)-manifest-vars
	rm $(BLD)-manifest-vars.sav

gather-linux-snapshot: gather-apr-1xbranch gather-aprutil-1xbranch \
		      gather-httpd-2xbranch gather-openssl-110branch \
		      gather-nghttp2-master gather-brotli-master \
		      gather-httpdtest-trunk
	mv $(BLD)-manifest-vars $(BLD)-manifest-vars.sav
	sort < $(BLD)-manifest-vars.sav > $(BLD)-manifest-vars
	rm $(BLD)-manifest-vars.sav

gather-linux-bleed:   gather-apr-trunk \
		      gather-httpd-trunk gather-openssl-master \
		      gather-nghttp2-master gather-brotli-master \
		      gather-httpdtest-trunk
	mv $(BLD)-manifest-vars $(BLD)-manifest-vars.sav
	sort < $(BLD)-manifest-vars.sav > $(BLD)-manifest-vars
	rm $(BLD)-manifest-vars.sav

ifeq "$(BLD)" "release"
tcnative: gather-tcnative-release
else
tcnative: gather-tcnative-trunk
endif

