# Pivotal OSS Build Schema for Apache HTTP Server
#
# Copyright (C) 2017-Present Pivotal Software, Inc. All rights reserved.
#
# This program and the accompanying materials are made available under
# the terms of the under the Apache License, Version 2.0 (the "License”);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Makefile.preconfig : Prepare configuration scripts of packages from source
#                      control where autoconf etc have not been invoked yet
#                      (typical of checkouts from source control)
#
# BLD defines the build type: release - candidate - snapshot - bleed
#
# This makefile is run after Makefile.gather from the source directory root,
# and must be performed only upon updates to the source packages as indicated
# by manifest changes.
#
# The result of this step is suitable for archive or escrow and distribution
# to multiple build systems, beginning at the Makefile.build step.

BLD=release

include $(BLD)-manifest-vars

all: prepare-linux

pre-preconfig:
	echo Preparing $(BLD) Source Trees


ifndef apr_srcdir
preconfig-apr: pre-preconfig
with_apr=
else
with_apr=--with-apr=../$(apr_srcdir)
$(apr_srcdir)/configure: $(apr_srcdir)/configure.in 
	cd $(apr_srcdir) && \
	  ./buildconf && \
	cd ..

preconfig-apr: pre-preconfig $(apr_srcdir)/configure
endif


ifndef apriconv_srcdir
with_apriconv=
preconfig-apriconv: preconfig-apr
else
with_apriconv=--with-apr-iconv=../$(apriconv_srcdir)
$(apriconv_srcdir)/configure: $(apriconv_srcdir)/configure.in 
	cd $(apriconv_srcdir) && \
	  ./buildconf $(with_apr) && \
	cd ..

preconfig-apriconv: preconfig-apr $(apriconv_srcdir)/configure
endif


ifndef aprutil_srcdir
with_aprutil=
preconfig-aprutil: preconfig-apr
else
with_aprutil=--with-apr-util=../$(aprutil_srcdir)
$(aprutil_srcdir)/configure: $(aprutil_srcdir)/configure.in 
	cd $(aprutil_srcdir) && \
	  ./buildconf $(with_apr) $(with_apriconv)&& \
	cd ..

preconfig-aprutil: preconfig-apr $(aprutil_srcdir)/configure
endif


ifndef httpd_srcdir
preconfig-httpd: preconfig-aprutil
else
$(httpd_srcdir)/configure: $(httpd_srcdir)/configure.in 
	cd $(httpd_srcdir) && \
	  ./buildconf $(with_apr) $(with_aprutil) && \
	cd ..

preconfig-httpd: preconfig-aprutil $(httpd_srcdir)/configure
endif


ifndef tcnative_srcdir
preconfig-tcnative: pre-preconfig
else
$(tcnative_srcdir)/native/configure: $(tcnative_srcdir)/native/configure.in 
	cd $(tcnative_srcdir)/native && \
	  ./buildconf --with-apr=../../$(apr_srcdir) && \
	cd ../..

preconfig-tcnative: preconfig-apr $(tcnative_srcdir)/native/configure
endif


preconfig-httpdtest: pre-preconfig
#	Apparently a noop


ifndef openssl_srcdir
preconfig-openssl: pre-preconfig
else
$(openssl_srcdir)/Makefile: $(openssl_srcdir)/Configure 
	cd $(openssl_srcdir) && \
	  ./Configure dist shared && \
	  $(MAKE) depend && \
	cd ..

preconfig-openssl: pre-preconfig $(openssl_srcdir)/Makefile
endif


ifndef nghttp2_srcdir
preconfig-nghttp2: pre-preconfig
else
$(nghttp2_srcdir)/configure: $(nghttp2_srcdir)/configure.ac
	cd $(nghttp2_srcdir) && \
	   autoreconf -i && \
	   automake && \
	   autoconf && \
	cd ..

preconfig-nghttp2: pre-preconfig $(nghttp2_srcdir)/configure
endif


ifndef brotli_srcdir
preconfig-brotli: pre-preconfig
else
$(brotli_srcdir)/configure: $(brotli_srcdir)/configure.ac
	cd $(brotli_srcdir) && \
	  ./bootstrap && \
	  autoreconf -i --force && \
	  automake && \
	  autoconf && \
	cd ..

preconfig-brotli: pre-preconfig $(brotli_srcdir)/configure
endif


ifndef curl_srcdir
preconfig-curl: pre-preconfig
else
$(curl_srcdir)/configure: $(curl_srcdir)/configure.ac
	cd $(curl_srcdir) && \
	  ./buildconf && \
	cd ..

preconfig-curl: pre-preconfig $(curl_srcdir)/configure
endif


ifndef expat_srcdir
preconfig-expat: pre-preconfig
else
$(expat_srcdir)/expat/configure: $(expat_srcdir)/expat/configure.ac \
				 $(expat_srcdir)/expat/Makefile.am
	-mkdir $(expat_srcdir)/expat/m4 2>/dev/null
	cd $(expat_srcdir)/expat && \
	  ./buildconf.sh && \
	cd ../..

preconfig-expat: pre-preconfig $(expat_srcdir)/expat/configure
endif


ifndef jansson_srcdir
preconfig-jansson: pre-preconfig
else
$(jansson_srcdir)/configure: $(jansson_srcdir)/configure.ac
	cd $(jansson_srcdir) && \
	  autoreconf -i --force && \
	  automake && \
	  autoconf && \
	cd ..

preconfig-jansson: pre-preconfig $(jansson_srcdir)/configure
endif


ifndef pcre_srcdir
preconfig-pcre: pre-preconfig
else
$(pcre_srcdir)/configure: $(pcre_srcdir)/configure.ac
	cd $(pcre_srcdir) && \
	  ./autogen.sh && \
	cd ..

preconfig-pcre: pre-preconfig $(pcre_srcdir)/configure
endif


ifndef libxml2_srcdir
preconfig-libxml2: pre-preconfig
else
$(libxml2_srcdir)/configure: $(libxml2_srcdir)/configure.ac
	cd $(libxml2_srcdir) && \
	  NOCONFIGURE=1 ./autogen.sh && \
	cd ..

preconfig-libxml2: pre-preconfig $(libxml2_srcdir)/configure
endif


preconfig-zlib: pre-preconfig


preconfig-lua: pre-preconfig


prepare-linux: preconfig-apr preconfig-apriconv preconfig-aprutil \
		preconfig-httpdtest preconfig-openssl preconfig-nghttp2 \
		preconfig-brotli preconfig-expat preconfig-pcre \
		preconfig-zlib preconfig-libxml2 preconfig-lua \
		preconfig-curl preconfig-jansson preconfig-httpd \
		preconfig-tcnative 
