# VMware OSS Build Schema for Apache HTTP Server
# 
# Copyright (c) 2017-2021 VMware, Inc.
#
# This program and the accompanying materials are made available under
# the terms of the under the Apache License, Version 2.0 (the "License”);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Makefile.download : Gather source code packages or (source checkouts)
#                     for all packages into the source tree based on
#                     the manifest file
#
# BLD defines the build type: release - candidate - snapshot - bleed
#
# This makefile is run first from the source directory root, and must be
# performed following updates to the manifest (list of source packages.)
# Makefile.preconfig in the same directory should follow immediately.

BLD=release

include $(BLD)-manifest-vars

all: download-all


$(httpdtest_srcdir):
	svn co -q -r $(httpdtest_rev) $(httpdtest_srcpath) $(httpdtest_srcdir)


$(httpd_srcdir):
ifdef httpd_pkg
	  if test ! -d pkgs; then mkdir pkgs; fi
	  cd pkgs && \
	  wget -nv $(httpd_srcpath)/$(httpd_pkg) && \
	  wget -nv $(httpd_srcpath)/$(httpd_pkg).asc && \
	  cd .. && \
	  tar -xjf pkgs/$(httpd_pkg)
else
	  svn co -q -r $(httpd_rev) $(httpd_srcpath) $(httpd_srcdir)
endif


$(tcnative_srcdir):
ifdef tcnative_pkg
	  if test ! -d pkgs; then mkdir pkgs; fi
	  cd pkgs && \
	  wget -nv $(tcnative_srcpath)/$(tcnative_pkg) && \
	  wget -nv $(tcnative_srcpath)/$(tcnative_pkg).asc && \
	  cd .. && \
	  tar -xzf pkgs/$(tcnative_pkg)
else
	  git clone -q $(tcnative_srcpath).git -n -b $(tcnative_ver) $(tcnative_srcdir) && \
	  cd $(tcnative_srcdir) && git checkout -q $(tcnative_rev) && cd ..
endif


$(apr_srcdir):
ifdef apr_pkg
	  if test ! -d pkgs; then mkdir pkgs; fi
	  cd pkgs && \
	  wget -nv $(apr_srcpath)/$(apr_pkg) && \
	  wget -nv $(apr_srcpath)/$(apr_pkg).asc && \
	  cd .. && \
	  tar -xjf pkgs/$(apr_pkg)
else
	  svn co -q -r $(apr_rev) $(apr_srcpath) $(apr_srcdir)
endif


$(apriconv_srcdir):
ifdef apriconv_pkg
	  if test ! -d pkgs; then mkdir pkgs; fi
	  cd pkgs && \
	  wget -nv $(apriconv_srcpath)/$(apriconv_pkg) && \
	  wget -nv $(apriconv_srcpath)/$(apriconv_pkg.asc) && \
	  cd .. && \
	  tar -xjf pkgs/$(apriconv_pkg)
else
	  svn co -q -r $(apriconv_rev) $(apriconv_srcpath) $(apriconv_srcdir)
endif


$(aprutil_srcdir):
ifdef aprutil_pkg
	  if test ! -d pkgs; then mkdir pkgs; fi
	  cd pkgs && \
	  wget -nv $(aprutil_srcpath)/$(aprutil_pkg) && \
	  wget -nv $(aprutil_srcpath)/$(aprutil_pkg).asc && \
	  cd .. && \
	  tar -xjf pkgs/$(aprutil_pkg)
else
	  svn co -q -r $(aprutil_rev) $(aprutil_srcpath) $(aprutil_srcdir)
endif


# external/perl/Text-Template packages under the Artistic license 
# do not conform to an Apache-licensed source package license
# (by the determination by the ASF)
$(openssl_srcdir):
ifdef openssl_pkg
	  if test ! -d pkgs; then mkdir pkgs; fi
	  cd pkgs && \
	  wget -nv $(openssl_srcpath)/$(openssl_pkg) && \
	  wget -nv $(openssl_srcpath)/$(openssl_pkg).asc && \
	  cd .. && \
	  tar -xzf pkgs/$(openssl_pkg)
else
	  git clone -q $(openssl_srcpath).git -n -b $(openssl_ver) $(openssl_srcdir) && \
	  cd $(openssl_srcdir) && git checkout -q $(openssl_rev) && cd ..
endif
	  rm -rf $(openssl_srcdir)/external/perl/*
	  touch $(openssl_srcdir)/external/perl/MODULES.txt


$(nghttp2_srcdir):
ifdef nghttp2_pkg
	  if test ! -d pkgs; then mkdir pkgs; fi
	  cd pkgs && \
	  wget -nv $(nghttp2_srcpath)/$(nghttp2_pkg) && \
	  cd .. && \
	  tar -xjf pkgs/$(nghttp2_pkg)
else
	  git clone -q $(nghttp2_srcpath).git -n -b $(nghttp2_ver) $(nghttp2_srcdir) && \
	  cd $(nghttp2_srcdir) && git checkout -q $(nghttp2_rev) && cd ..
endif


$(brotli_srcdir):
ifdef brotli_pkg
	  if test ! -d pkgs; then mkdir pkgs; fi
	  cd pkgs && \
	  wget -nv $(brotli_srcpath) -O $(brotli_pkg) && \
	  cd .. && \
	  tar -xzf pkgs/$(brotli_pkg)
else
	  git clone -q $(brotli_srcpath).git -n -b $(brotli_ver) $(brotli_srcdir) && \
	  cd $(brotli_srcdir) && git checkout -q $(brotli_rev) && cd ..
endif


$(curl_srcdir):
ifdef curl_pkg
	  if test ! -d pkgs; then mkdir pkgs; fi
	  cd pkgs && \
	  wget -nv $(curl_srcpath)/$(curl_pkg) && \
	  wget -nv $(curl_srcpath)/$(curl_pkg).asc && \
	  cd .. && \
	  tar -xjf pkgs/$(curl_pkg)
else
	  git clone -q $(curl_srcpath).git -n -b $(curl_ver) $(curl_srcdir) && \
	  cd $(curl_srcdir) && git checkout -q $(curl_rev) && cd ..
endif


$(openldap_srcdir):
ifdef openldap_pkg
	  if test ! -d pkgs; then mkdir pkgs; fi
	  cd pkgs && \
	  wget -nv $(openldap_srcpath)/$(openldap_pkg) && \
	  openldap_sig=`echo $(openldap_pkg) | sed 's#\.tgz#.sha1#'` && \
	  wget -nv $(openldap_srcpath)/$$openldap_sig && \
	  cd .. && \
	  tar -xzf pkgs/$(openldap_pkg)
else
	  # git clone -q -b OPENLDAP_REL_ENG_$(openldap_ver)
	  git clone -q $(openldap_srcpath) -n -b $(openldap_ver) $(openldap_srcdir) && \
	  cd $(openldap_srcdir) && git checkout -q $(openldap_rev) && cd ..
endif


$(expat_srcdir):
ifdef expat_pkg
	  if test ! -d pkgs; then mkdir pkgs; fi
	  cd pkgs && \
	  wget -nv $(expat_srcpath) -O $(expat_pkg) && \
	  cd .. && \
	  tar -xzf pkgs/$(expat_pkg)
else
	  git clone -q $(expat_srcpath).git -n -b $(expat_ver) $(expat_srcdir) && \
	  cd $(expat_srcdir) && git checkout -q $(expat_rev) && cd ..
endif


$(pcre_srcdir):
ifdef pcre_pkg
	  if test ! -d pkgs; then mkdir pkgs; fi
	  cd pkgs && \
	  wget -nv $(pcre_srcpath)/$(pcre_pkg) && \
	  wget -nv $(pcre_srcpath)/$(pcre_pkg).sig && \
	  cd .. && \
	  tar -xjf pkgs/$(pcre_pkg)
else
	  svn co -q -r $(pcre_rev) $(pcre_srcpath) $(pcre_srcdir)
endif


$(jansson_srcdir):
ifdef jansson_pkg
	  if test ! -d pkgs; then mkdir pkgs; fi
	  cd pkgs && \
	  wget -nv $(jansson_srcpath) -O $(jansson_pkg) && \
	  cd .. && \
	  tar -xzf pkgs/$(jansson_pkg)
else
	  git clone -q $(jansson_srcpath).git -n -b $(jansson_ver) $(jansson_srcdir) && \
	  cd $(jansson_srcdir) && git checkout -q $(jansson_rev) && cd ..
endif


$(libxml2_srcdir):
ifdef libxml2_pkg
	  if test ! -d pkgs; then mkdir pkgs; fi
	  cd pkgs && \
	  wget -nv $(libxml2_srcpath) -O $(libxml2_pkg) && \
	  cd .. && \
	  tar -xjf pkgs/$(libxml2_pkg)
else
	  git clone -q $(libxml2_srcpath).git -n -b $(libxml2_ver) $(libxml2_srcdir) && \
	  cd $(libxml2_srcdir) && git checkout -q $(libxml2_rev) && cd ..
endif


$(lua_srcdir):
ifdef lua_pkg
	  if test ! -d pkgs; then mkdir pkgs; fi
	  cd pkgs && \
	  wget -nv $(lua_srcpath)/$(lua_pkg) && \
	  cd ..
	  tar -xzf pkgs/$(lua_pkg)
endif


$(zlib_srcdir):
ifdef zlib_pkg
	  if test ! -d pkgs; then mkdir pkgs; fi
	  cd pkgs && \
	  wget -nv $(zlib_srcpath)/$(zlib_pkg) && \
	  wget -nv $(zlib_srcpath)/$(zlib_pkg).asc && \
	  cd .. && \
	  tar -xzf pkgs/$(zlib_pkg)
else
	  git clone -q $(zlib_srcpath).git -n -b $(zlib_ver) $(zlib_srcdir) && \
	  cd $(zlib_srcdir) && git checkout -q $(zlib_rev) && cd ..
endif


download-all:	$(httpdtest_srcdir) $(httpd_srcdir) $(tcnative_srcdir) \
		$(apr_srcdir) $(apriconv_srcdir) $(aprutil_srcdir) \
		$(openssl_srcdir) $(nghttp2_srcdir) $(brotli_srcdir) \
		$(curl_srcdir) $(openldap_srcdir) $(expat_srcdir) \
		$(pcre_srcdir) $(jansson_srcdir) $(libxml2_srcdir) \
		$(lua_srcdir) $(zlib_srcdir)

